name: publiccms

services:
  publiccms:
    build: .
    image: seanly/appset:publiccms-v4
    container_name: publiccms
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data/publiccms:/data/publiccms
    depends_on:
      - "mysql"
  mysql:
    image: seanly/appset:mysql-8.0.39-oracle-1
    container_name: mysql-cms
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/mysql-config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password!@#
      - MYSQL_DATABASE=publiccms
      - MYSQL_USER=publiccms
      - MYSQL_PASSWORD=password!@#
    command:
      - --server-id=1
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 5
  nginx:
    image: seanly/appset:nginx-1.27.1-ubi9.5-1
    container_name: nginx-cms
    ports:
      - "80:80"
    volumes:
      - ./data/nginx-config:/etc/nginx/conf.d
      - ./data/publiccms:/data/publiccms

volumes:
  mysql-data:
